app:
  base-url: http://localhost:8080

spring:
  datasource:
    url: jdbc:postgresql://${DB_HOST:localhost}:${DB_PORT:5437}/${DB_NAME:tradingbot}
    username: ${DB_USERNAME:tradingbot}
    password: ${DB_PASSWORD:tradingbot}
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: validate
    open-in-view: false
  liquibase:
    change-log: classpath:db/changelog/db.changelog-master.xml

telegram:
  bot-token: ${TELEGRAM_BOT_TOKEN}
  bot-username: ${TELEGRAM_BOT_USERNAME}

exchange:
  binance:
    base-url: https://fapi.binance.com
  bybit:
    base-url: https://api.bybit.com

alerts:
  symbols:
    top-n: 50
    update-interval: PT3H
  price:
    interval: PT30S
    candle-interval: 15m
    candle-limit: 1
    threshold: 0.5
    cooldown: 30m
    debug-mode: true
