spring:
  datasource:
    url: jdbc:postgresql://localhost:5437/tradingbot
    username: ${DB_USERNAME:tradingbot}
    password: ${DB_PASSWORD:tradingbot}
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: validate
    open-in-view: false
  liquibase:
    change-log: classpath:db/changelog/db.changelog-master.xml

telegram:
  bot-token: ${TELEGRAM_BOT_TOKEN}
  bot-username: ${TELEGRAM_BOT_USERNAME}
  chat-id: ${TELEGRAM_CHAT_ID}

alerts:
  symbols:
    - BTCUSDT
    - ETHUSDT
